# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QPixmap
from PyQt5.QtWidgets import QLineEdit


class Ui_Edit(object):
    def setupUi(self, Edit):
        Edit.setObjectName("Edit")
        Edit.resize(400, 300)
        Edit.setMinimumSize(QtCore.QSize(400, 300))
        Edit.setMaximumSize(QtCore.QSize(400, 300))
        icon = QIcon()
        icon.addPixmap(QPixmap("../gui/resource/shaco_logo.jpg"), QIcon.Normal, QIcon.Off)
        self.setWindowIcon(icon)
        self.gridLayoutWidget = QtWidgets.QWidget(Edit)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 381, 174))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.mailLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mailLabel.setObjectName("mailLabel")
        self.gridLayout.addWidget(self.mailLabel, 3, 0, 1, 1)
        self.codeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.codeLabel.setObjectName("codeLabel")
        self.gridLayout.addWidget(self.codeLabel, 5, 0, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 1, 0, 1, 1)
        self.mailEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.mailEdit.setObjectName("mailEdit")
        self.gridLayout.addWidget(self.mailEdit, 3, 1, 1, 1)
        self.passwordStatus = QtWidgets.QLabel(self.gridLayoutWidget)
        self.passwordStatus.setText("")
        self.passwordStatus.setObjectName("passwordStatus")
        self.gridLayout.addWidget(self.passwordStatus, 1, 2, 1, 1)
        self.codeEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.codeEdit.setObjectName("codeEdit")
        self.gridLayout.addWidget(self.codeEdit, 5, 1, 1, 1)
        self.passwordEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.passwordEdit.setObjectName("passwordEdit")
        self.gridLayout.addWidget(self.passwordEdit, 1, 1, 1, 1)
        self.mailStatus = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mailStatus.setText("")
        self.mailStatus.setObjectName("mailStatus")
        self.gridLayout.addWidget(self.mailStatus, 3, 2, 1, 1)
        self.codeStatus = QtWidgets.QLabel(self.gridLayoutWidget)
        self.codeStatus.setText("")
        self.codeStatus.setObjectName("codeStatus")
        self.gridLayout.addWidget(self.codeStatus, 5, 2, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 1)
        self.gridLayout.setColumnMinimumWidth(1, 5)
        self.gridLayout.setColumnMinimumWidth(2, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout.setColumnStretch(2, 2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Edit)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 220, 274, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(80)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sendButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.confirmButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.confirmButton)

        self.retranslateUi(Edit)
        QtCore.QMetaObject.connectSlotsByName(Edit)
        # 设置背景
        self.backgroundLabel = QtWidgets.QLabel(Edit)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 500, 300))
        self.backgroundLabel.setPixmap(QtGui.QPixmap("resources/pic/whiteBackground.jpg"))
        self.backgroundLabel.setScaledContents(True)
        self.backgroundLabel.lower()

        # 设置提示
        self.mailEdit.setToolTip('输入您未注册的邮箱')
        self.passwordEdit.setToolTip('密码长度不超过12')
        self.codeEdit.setToolTip('未收到验证码？请检查邮箱是否正确')


        # 设置edit
        self.passwordEdit.setEchoMode(QLineEdit.Password)
        self.passwordEdit.setClearButtonEnabled(True)
        self.mailEdit.setClearButtonEnabled(True)

        # 开始QSS设置
        self.setQSS()

    def setQSS(self):
        edit_qss = '''QLineEdit{
                                         border:1px solid gray;
                                         width:300px;
                                         border-radius:10px;
                                         padding:2px 4px; }'''
        self.mailEdit.setStyleSheet(edit_qss)
        self.passwordEdit.setStyleSheet(edit_qss)
        self.codeEdit.setStyleSheet(edit_qss)

        button_qss = '''     QPushButton{  
                                     border:2px solid #F3F3F5;   
                                     color:black;         
                                     font-size:12px;         
                                     height:40px;         
                                     padding-left:5px;         
                                     padding-right:10px;         
                                     }     
                                                QPushButton:hover{         
                                     color:brown;         
                                     border:2px solid #F3F3F5;         
                                     border-radius:10px;         
                                     background:LightGray;     
                                     } '''
        self.confirmButton.setStyleSheet(button_qss)
        self.sendButton.setStyleSheet(button_qss)

        label_qss = '''QLabel{
                                        color:black
                                        }
                                        QLabel:hover{
                                        color:gray
                                        }
                            '''
        self.mailLabel.setStyleSheet(label_qss)
        self.mailStatus.setStyleSheet(label_qss)
        self.passwordLabel.setStyleSheet(label_qss)
        self.passwordStatus.setStyleSheet(label_qss)
        self.codeLabel.setStyleSheet(label_qss)
        self.codeStatus.setStyleSheet(label_qss)

        self.setWindowOpacity(0.95)  # 设置窗口透明度
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)  # 设置窗口背景透明

    def retranslateUi(self, Edit):
        _translate = QtCore.QCoreApplication.translate
        Edit.setWindowTitle(_translate("Edit", "修改密码"))
        self.mailLabel.setText(_translate("Edit", "邮箱地址"))
        self.codeLabel.setText(_translate("Edit", "验证码"))
        self.passwordLabel.setText(_translate("Edit", "新密码"))
        self.sendButton.setText(_translate("Edit", "发送验证邮件"))
        self.confirmButton.setText(_translate("Edit", "确定"))
