# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Edit(object):
    def setupUi(self, Edit):
        Edit.setObjectName("Edit")
        Edit.resize(600, 300)
        Edit.setMinimumSize(QtCore.QSize(600, 300))
        Edit.setMaximumSize(QtCore.QSize(600, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Shaco_Logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Edit.setWindowIcon(icon)
        Edit.setStyleSheet("")
        self.sendButton = QtWidgets.QPushButton(Edit)
        self.sendButton.setGeometry(QtCore.QRect(440, 120, 111, 30))
        self.sendButton.setObjectName("sendButton")
        self.mailLabel = QtWidgets.QLabel(Edit)
        self.mailLabel.setGeometry(QtCore.QRect(50, 130, 72, 15))
        self.mailLabel.setObjectName("mailLabel")
        self.codeLabel = QtWidgets.QLabel(Edit)
        self.codeLabel.setGeometry(QtCore.QRect(60, 190, 72, 15))
        self.codeLabel.setObjectName("codeLabel")
        self.mailEdit = QtWidgets.QLineEdit(Edit)
        self.mailEdit.setGeometry(QtCore.QRect(130, 120, 300, 30))
        self.mailEdit.setObjectName("mailEdit")
        self.codeEdit = QtWidgets.QLineEdit(Edit)
        self.codeEdit.setGeometry(QtCore.QRect(130, 180, 300, 30))
        self.codeEdit.setObjectName("codeEdit")
        self.confirmButton = QtWidgets.QPushButton(Edit)
        self.confirmButton.setGeometry(QtCore.QRect(230, 270, 93, 28))
        self.confirmButton.setObjectName("confirmButton")
        self.newpasswordLabel = QtWidgets.QLabel(Edit)
        self.newpasswordLabel.setGeometry(QtCore.QRect(60, 60, 61, 21))
        self.newpasswordLabel.setObjectName("newpasswordLabel")
        self.newpasswordEdit = QtWidgets.QLineEdit(Edit)
        self.newpasswordEdit.setGeometry(QtCore.QRect(130, 60, 300, 30))
        self.newpasswordEdit.setObjectName("newpasswordEdit")
        self.newpasswordStatus = QtWidgets.QLabel(Edit)
        self.newpasswordStatus.setGeometry(QtCore.QRect(130, 90, 331, 16))
        self.newpasswordStatus.setText("")
        self.newpasswordStatus.setObjectName("newpasswordStatus")
        self.codeStatus = QtWidgets.QLabel(Edit)
        self.codeStatus.setGeometry(QtCore.QRect(130, 220, 411, 21))
        self.codeStatus.setText("")
        self.codeStatus.setObjectName("codeStatus")
        self.mailStatus = QtWidgets.QLabel(Edit)
        self.mailStatus.setGeometry(QtCore.QRect(140, 160, 291, 16))
        self.mailStatus.setText("")
        self.mailStatus.setObjectName("mailStatus")

        self.retranslateUi(Edit)
        QtCore.QMetaObject.connectSlotsByName(Edit)

    def retranslateUi(self, Edit):
        _translate = QtCore.QCoreApplication.translate
        Edit.setWindowTitle(_translate("Edit", "修改密码"))
        self.sendButton.setText(_translate("Edit", "发送验证邮件"))
        self.mailLabel.setText(_translate("Edit", "邮箱地址"))
        self.codeLabel.setText(_translate("Edit", "验证码"))
        self.confirmButton.setText(_translate("Edit", "确定"))
        self.newpasswordLabel.setText(_translate("Edit", "新密码"))
