# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(900, 500)
        login.setMinimumSize(QtCore.QSize(600, 500))
        login.setMaximumSize(QtCore.QSize(900, 500))
        self.mailEdit = QtWidgets.QTextEdit(login)
        self.mailEdit.setGeometry(QtCore.QRect(220, 220, 320, 40))
        self.mailEdit.setObjectName("mailEdit")
        self.passwordEdit = QtWidgets.QTextEdit(login)
        self.passwordEdit.setGeometry(QtCore.QRect(220, 300, 320, 40))
        self.passwordEdit.setObjectName("passwordEdit")
        self.loginButton = QtWidgets.QPushButton(login)
        self.loginButton.setGeometry(QtCore.QRect(230, 420, 93, 28))
        self.loginButton.setObjectName("loginButton")
        self.registerButton = QtWidgets.QPushButton(login)
        self.registerButton.setGeometry(QtCore.QRect(430, 420, 93, 28))
        self.registerButton.setObjectName("registerButton")
        self.titleLabel = QtWidgets.QLabel(login)
        self.titleLabel.setGeometry(QtCore.QRect(280, 30, 150, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setMinimumSize(QtCore.QSize(150, 150))
        self.titleLabel.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.titleLabel.setMouseTracking(False)
        self.titleLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.titleLabel.setObjectName("titleLabel")
        self.logoView = QtWidgets.QGraphicsView(login)
        self.logoView.setGeometry(QtCore.QRect(580, 20, 256, 192))
        self.logoView.setObjectName("logoView")
        self.mailLabel = QtWidgets.QLabel(login)
        self.mailLabel.setGeometry(QtCore.QRect(150, 230, 72, 15))
        self.mailLabel.setObjectName("mailLabel")
        self.passwordLabel = QtWidgets.QLabel(login)
        self.passwordLabel.setGeometry(QtCore.QRect(150, 310, 72, 15))
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordStatus = QtWidgets.QLabel(login)
        self.passwordStatus.setGeometry(QtCore.QRect(220, 360, 321, 20))
        self.passwordStatus.setText("")
        self.passwordStatus.setObjectName("passwordStatus")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Form"))
        self.loginButton.setText(_translate("login", "登录"))
        self.registerButton.setText(_translate("login", "注册"))
        self.titleLabel.setText(_translate("login", "ShacoRoom"))
        self.mailLabel.setText(_translate("login", "邮箱"))
        self.passwordLabel.setText(_translate("login", "密码"))
