# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verifyGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Verify(object):
    def setupUi(self, Verify):
        Verify.setObjectName("Verify")
        Verify.resize(600, 300)
        Verify.setMinimumSize(QtCore.QSize(600, 300))
        Verify.setMaximumSize(QtCore.QSize(600, 300))
        self.sendButton = QtWidgets.QPushButton(Verify)
        self.sendButton.setGeometry(QtCore.QRect(430, 90, 101, 28))
        self.sendButton.setObjectName("sendButton")
        self.mailLabel = QtWidgets.QLabel(Verify)
        self.mailLabel.setGeometry(QtCore.QRect(50, 100, 72, 15))
        self.mailLabel.setObjectName("mailLabel")
        self.codeLabel = QtWidgets.QLabel(Verify)
        self.codeLabel.setGeometry(QtCore.QRect(60, 140, 72, 15))
        self.codeLabel.setObjectName("codeLabel")
        self.mailEdit = QtWidgets.QLineEdit(Verify)
        self.mailEdit.setGeometry(QtCore.QRect(130, 90, 291, 31))
        self.mailEdit.setObjectName("mailEdit")
        self.codeEdit = QtWidgets.QLineEdit(Verify)
        self.codeEdit.setGeometry(QtCore.QRect(130, 130, 291, 31))
        self.codeEdit.setObjectName("codeEdit")
        self.statusBrowser = QtWidgets.QTextBrowser(Verify)
        self.statusBrowser.setGeometry(QtCore.QRect(430, 130, 141, 31))
        self.statusBrowser.setObjectName("statusBrowser")
        self.confirmButton = QtWidgets.QPushButton(Verify)
        self.confirmButton.setGeometry(QtCore.QRect(250, 220, 93, 28))
        self.confirmButton.setObjectName("confirmButton")

        self.retranslateUi(Verify)
        QtCore.QMetaObject.connectSlotsByName(Verify)

    def retranslateUi(self, Verify):
        _translate = QtCore.QCoreApplication.translate
        Verify.setWindowTitle(_translate("Verify", "Form"))
        self.sendButton.setText(_translate("Verify", "发送验证邮件"))
        self.mailLabel.setText(_translate("Verify", "邮箱地址"))
        self.codeLabel.setText(_translate("Verify", "验证码"))
        self.confirmButton.setText(_translate("Verify", "确定"))
