# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verifyGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Verify(object):
    def setupUi(self, Verify):
        Verify.setObjectName("Verify")
        Verify.resize(600, 300)
        Verify.setMinimumSize(QtCore.QSize(600, 300))
        Verify.setMaximumSize(QtCore.QSize(600, 300))
        self.sendButton = QtWidgets.QPushButton(Verify)
        self.sendButton.setGeometry(QtCore.QRect(440, 170, 100, 30))
        self.sendButton.setObjectName("sendButton")
        self.mailLabel = QtWidgets.QLabel(Verify)
        self.mailLabel.setGeometry(QtCore.QRect(50, 180, 72, 15))
        self.mailLabel.setObjectName("mailLabel")
        self.codeLabel = QtWidgets.QLabel(Verify)
        self.codeLabel.setGeometry(QtCore.QRect(60, 220, 72, 15))
        self.codeLabel.setObjectName("codeLabel")
        self.mailEdit = QtWidgets.QLineEdit(Verify)
        self.mailEdit.setGeometry(QtCore.QRect(130, 170, 300, 30))
        self.mailEdit.setObjectName("mailEdit")
        self.codeEdit = QtWidgets.QLineEdit(Verify)
        self.codeEdit.setGeometry(QtCore.QRect(130, 210, 300, 30))
        self.codeEdit.setObjectName("codeEdit")
        self.codeStatus = QtWidgets.QTextBrowser(Verify)
        self.codeStatus.setGeometry(QtCore.QRect(440, 210, 150, 30))
        self.codeStatus.setObjectName("codeStatus")
        self.confirmButton = QtWidgets.QPushButton(Verify)
        self.confirmButton.setGeometry(QtCore.QRect(230, 270, 93, 28))
        self.confirmButton.setObjectName("confirmButton")
        self.nameLabel = QtWidgets.QLabel(Verify)
        self.nameLabel.setGeometry(QtCore.QRect(50, 140, 72, 15))
        self.nameLabel.setObjectName("nameLabel")
        self.passwordLabel = QtWidgets.QLabel(Verify)
        self.passwordLabel.setGeometry(QtCore.QRect(50, 100, 72, 15))
        self.passwordLabel.setObjectName("passwordLabel")
        self.nameEdit = QtWidgets.QLineEdit(Verify)
        self.nameEdit.setGeometry(QtCore.QRect(130, 90, 300, 30))
        self.nameEdit.setObjectName("nameEdit")
        self.passwordEdit = QtWidgets.QLineEdit(Verify)
        self.passwordEdit.setGeometry(QtCore.QRect(130, 130, 300, 30))
        self.passwordEdit.setObjectName("passwordEdit")
        self.passwordStatus = QtWidgets.QTextBrowser(Verify)
        self.passwordStatus.setGeometry(QtCore.QRect(440, 130, 150, 30))
        self.passwordStatus.setObjectName("passwordStatus")
        self.nameStatus = QtWidgets.QTextBrowser(Verify)
        self.nameStatus.setGeometry(QtCore.QRect(440, 90, 150, 30))
        self.nameStatus.setObjectName("nameStatus")

        self.retranslateUi(Verify)
        self.codeEdit.textChanged['QString'].connect(self.codeStatus.show)
        self.passwordEdit.textChanged['QString'].connect(self.passwordStatus.show)
        self.nameEdit.textChanged['QString'].connect(self.nameStatus.show)
        QtCore.QMetaObject.connectSlotsByName(Verify)

    def retranslateUi(self, Verify):
        _translate = QtCore.QCoreApplication.translate
        Verify.setWindowTitle(_translate("Verify", "Form"))
        self.sendButton.setText(_translate("Verify", "发送验证邮件"))
        self.mailLabel.setText(_translate("Verify", "邮箱地址"))
        self.codeLabel.setText(_translate("Verify", "验证码"))
        self.confirmButton.setText(_translate("Verify", "确定"))
        self.nameLabel.setText(_translate("Verify", "密码"))
        self.passwordLabel.setText(_translate("Verify", "用户名"))
